### ISSUE TITLE
Bluetooth HF Audio not working!

### ISSUE THREAD

**Issue by orionbg** [cm7sgt/android_device_samsung_galaxytab#1]
Bluetooth handsfree audio during a phone call is not working properly! The sound is heavily distorted!

**Comment by techomancer** [comment]
confirmed, working on it, but I have no idea why this is happening. It was also happening with Froyo kernel and JK5 RIL. I tried Samsung's binary libaudio from JQ1 and it didn't help either. For now it is a great mystery for me ;-(

**Comment by orionbg** [comment]
Is it possible to try with Samsung's BT driver?

**Comment by af974** [comment]
AudioBTID.csv under System/etc could help?

**Comment by cm7sgt** [comment]
I doubt it. I dont see it used by CM7.

**Comment by cm7sgt** [comment]
This should fix it https://github.com/cm7sgt/android_device_samsung_galaxytab/commit/82a144dccbcd02ac5cdda04c268a366663b41bb0
It will be included in today's release.
