### ISSUE TITLE
cpu frequencies

### ISSUE THREAD

**Issue by af974** [cm7sgt/android_device_samsung_galaxytab#10]
In cyanogen cpu setting , frequencies are not visible.

**Comment by chandradithya** [comment]
Well I think the kernel which he's using is just the basic one. He said he'll modify the kernel amd ass voodoo sound, 10pt multi touch and the Overclock capabily and upload the kernel.  :)
Correct me if im wrong. -_-

**Comment by af974** [comment]
The problem is that with Setcpu you can low the frequencies.

**Comment by cm7sgt** [comment]
It looks like the kernel does not export available frequencies in /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies

**Comment by af974** [comment]
Kernel works fine, as i said you can set low frequencies (not high, no OC support in kernel) with Setcpu, they don't work with Cyanogen setting->Performance.Not a big deal though, i thought you would know that.

**Comment by cm7sgt** [comment]
Fixed in https://github.com/cm7sgt/kernel-galaxytab-gb/commit/0885fa2ada3162a42a5d1a1e6620acab04be990c
