### ISSUE TITLE
SetCPU kinda unstable'ish,   bug with the kernel? 

### ISSUE THREAD

**Issue by chandradithya** [cm7sgt/android_device_samsung_galaxytab#11]
Well after the update to the new kernal, things have been faster thanks to OC support, but however I noticed my tempratures were going through the roof. Its at about 44.9°C now while charging. So I underclocked it from 1200Mhz to 600. And set cpu automatically showed the current freq below 600. And I also set governor to powersave (minimum being 200Mhz) but temp till shot up to 45.6° after that. When I opened setcpu it showed it was running at 1200, even after the governor being at power save between 200 - 600. 

What im right now afraid of is my phone exploding due to overheating :P
Whats the safe limit for the temp.

And oh. Im from india btw. Freaking hot here now that its summer, the reading above were taken with the room temp being 29°c

**Comment by cm7sgt** [comment]
Fixed in https://github.com/cm7sgt/kernel-galaxytab-gb/commit/c592f3560e647145b59beab94d9650f62c1e9713

**Comment by chandradithya** [comment]
Yeah. Thanks :)
