### ISSUE TITLE
Browser cannot download files by default

### ISSUE THREAD

**Issue by basak** [cm7sgt/android_device_samsung_galaxytab#12]
Thanks very much for your excellent work!

One problem is that the browser cannot download files. It says in a window entitled "No SD card" that "An SD card is required to download ...".

I don't have an external SD card installed, but I am able to do this in stock firmware without any problems.

This means that I can't install any apps directly from a file without going through adb to put it on internal storage manually.

Is this to do with the decision to mount the internal storage under /emmc, or a problem in the way that vold is configured? Is there a workaround for this? I can't find a way to configure the browser any differently.

**Comment by cm7sgt** [comment]
Insert SD card. http://www.newegg.com/Product/Product.aspx?Item=N82E16820220220

Or modify your /system/etc/vold.fstab or replace it with one Fabrizio posted here http://forum.xda-developers.com/showpost.php?p=14241686&postcount=681

External SD card is /mnt/sdcard like in every other Android or CM7 device.
Embedded MMC is /mnt/emmc.

**Comment by basak** [comment]
I understand that I can use one of two workarounds - either install an SD card or manually change vold.fstab.

I reported the bug because of the default behaviour. Are you saying that "every over Android or CM7 device" also cannot download anything inside the browser without an external SD card inserted? I don't care what the mount points are behind the scenes, I just think that the UI should work by default.

**Comment by cm7sgt** [comment]
Most people do have SD cards so it doesn't seem to be an issue. Other Android devices do need SD card as well and are usually sold with one already inserted.
There is no guarantee in CM7 vold that /mnt/sdcard/external_sd would be mounted after /mnt/sdcard and unmounted before it so I do not want to  set the mounts like this. And again, /mnt/sdcard is the external device everywhere else so most people and apps expect it this way. I know Samsung may be doing it differently but this is CM7 (Sparta!!!). I will post reversed vold.fstab as attachement in the first post so everyone who feels like it can replace it but the default will stay as it is.
