### ISSUE TITLE
2G APN not Working

### ISSUE THREAD

**Issue by alphamu** [cm7sgt/android_device_samsung_galaxytab#14]
My carrier has a 2G (EDGE) and I simply can't seem to connect to it.
Even MMS settings are not working.
The settings for Internet are:
APN: ufone.internet
Username: ufone
Password: ufone
APN Type: default

The settings for MMS are:
APN: ufone.mms
Username:
Password:
MMSC: http://www.ufonemms.com:80/
MMSC Proxy: 172.16.13.27:8080
APN Type: mms

**Comment by cm7sgt** [comment]
I tried setting Wireless&Settings->Mobile Networks->Use only 2G networks and my Tab dropped down to EDGE like it should. It also automatically switches to EDGE or GPRS when there is bad reception. So it seems 2G is working just fine. What radio are you using? For Euro tabs try JK5. Anything interesting in logcat?

**Comment by alphamu** [comment]
Everything i used was from the JQ1 firmware. are you saying i should use the phone frpm the JK5 firmware and try a reflash? My tab is the middle east tab but i run european stock frmware on it with no issues. Im not familiar with logcat. If that is a log file, where is it located?

**Comment by cm7sgt** [comment]
Just flash JK5 modem.bin with Heimdall. No need to reinstall anything else.
Logcat is a tool to see Android system log. You can run it in terminal on the device by simply running logcat command. You can also run it using adb from host system by running "adb logcat".
You can also try using this app  https://market.android.com/details?id=org.jtb.alogcat&feature=search_result

**Comment by alphamu** [comment]
Thanks cm7sgt, that did it.
Would you happen to know how I can get the screen off crt animation and the screen rotation animation?
