### ISSUE TITLE
Gingerbread Keyboard Keeps Losing Focus

### ISSUE THREAD

**Issue by alphamu** [cm7sgt/android_device_samsung_galaxytab#15]
Noticed while using the TalkBack keyboard that it keeps losing focus when typing.

**Comment by cm7sgt** [comment]
It seems like upstream issue. Please verify on other CM devices and submit to CM issue tracker.
see http://wiki.cyanogenmod.com/index.php?title=Howto:_Use_the_Issue_Tracker and http://code.google.com/p/cyanogenmod/issues/list
