### ISSUE TITLE
Bluetooth SCO (headeset profile) not working correctly 

### ISSUE THREAD

**Issue by cm7sgt** [cm7sgt/android_device_samsung_galaxytab#17]
Bluetooth SCO is broken. When paired with headset and making a call there is garbled noise sound on both sides of the conversation.

**Comment by alphamu** [comment]
I have the same issue. Headset is Jawbone 2. I can barely hear anyone at my end, I mostly get noise when the person speaks. The claim they can hear me loudly with a lot of noise as well.

Also when i connect to the bluetooth headset it says "Connected to phone audio" I dont know if this points to a problem or not.

**Comment by cm7sgt** [comment]
Yes, it is not working for everyone.

**Comment by cm7sgt** [comment]
This should fix it. https://github.com/cm7sgt/android_device_samsung_galaxytab/commit/82a144dccbcd02ac5cdda04c268a366663b41bb0 It should be included in today's release.
