### ISSUE TITLE
Answering Phone Calls Volume Problem

### ISSUE THREAD

**Issue by alphamu** [cm7sgt/android_device_samsung_galaxytab#19]
When I answer a call with my Galaxy tab, the volume is extremely low. I've made sure the in-call volume is at max.
The issue seems to be that there is no automatic recognition of the fact that we are on speaker. If I press the speaker button this problem goes away.

**Comment by cm7sgt** [comment]
The alsa mixer for Voice Call Path is set to SPK by default. If you press speaker button it will set it to SPK again. It does not change the volume. Are you sure pressing speaker button makes it louder?

**Comment by alphamu** [comment]
Yes, just tried it again, the volume is low when I answer the call and the speaker button is not selected. When I press the speaker button it makes a world of different to the call volume.

I have the JK5 modem installed and upgraded from JQ1

**Comment by cm7sgt** [comment]
This should fix it. https://github.com/cm7sgt/android_device_samsung_galaxytab/commit/4d31810201cb8a45efefbe2435ef91d5f019bcec
It will be included in todays release. Please test and reopen if still broken.
