### ISSUE TITLE
usb mounting fails

### ISSUE THREAD

**Issue by dynamohum** [cm7sgt/android_device_samsung_galaxytab#2]
When selecting "USB Connected" from dropdown status it immediately closes and returns to launcher. Logcat shows:

I/ActivityManager(  171): Starting: Intent { flg=0x10000000 cmp=com.android.systemui/.usb.UsbStorageActivity bnds=[0,180][600,268] } from pid -1
D/VoldCmdListener(   79): volume shared /mnt/sdcard ums
D/VoldCmdListener(   79): volume shared /mnt/emmc ums
W/InputManagerService(  171): Window already focused, ignoring focus gain of:
com.android.internal.view.IInputMethodClient$Stub$Proxy@405e3788

**Comment by techomancer** [comment]
Yep, working on it.

**Comment by cm7sgt** [comment]
Fixed in https://github.com/cm7sgt/kernel-galaxytab-gb/commit/00ab2f9a60cb14f8849ce010cdac0fc5d7b3d711
