### ISSUE TITLE
USB not detected

### ISSUE THREAD

**Issue by gtabber1117** [cm7sgt/android_device_samsung_galaxytab#22]
plug in usb, cannot tether or USB sdcard mount. attempted through Widgetsoid from the market, popup error message "plug in USB first" attempted through Extended controls through the app market, same error popup. 

attempted on Windows7, Windows Vista, Windows XP, Apple Leopard, and Ubuntu 11.04 machines, all same error, never get the "USB connected" in drop down menu. currently using beta 2011-06-21.

**Comment by techomancer** [comment]
this has been fixed several weeks ago. what device and kernel are you using? p1000n/l? if so it is broken there because of a bug in samsung's kernel.

**Comment by gtabber1117** [comment]
i am using the sgh-t849 for tmobile with the p1000 kernel and gsm modem,
should i reflash with a different kernel?
ps wifi rediculously slow compared to stock firm. speed drop from 11mbps to
2.5 on my home network. had 60%ish signal, now with this firm its like less
than 20

**Comment by cm7sgt** [comment]
wifi driver and firmware is the same as stock.

we will have new kernel soon with merged latest sph-p100 release from Samsung. They improved usb gadget/composite/ums a lot in there so maybe it will help with your issues.

for now i am just trying to sync repo to latest and github or kernel.org suck tonight.

**Comment by gtabber1117** [comment]
very fast reply lol thanks. how soon is soon? :D

**Comment by cm7sgt** [comment]
the merged kernel is used for couple releases now, USB storage seems to be quite stable, closing now.
