### ISSUE TITLE
Wlan Hotpot not working

### ISSUE THREAD

**Issue by Byrana** [cm7sgt/android_device_samsung_galaxytab#23]
I just tried to set up a hotspot but it just shows error.

**Comment by cm7sgt** [comment]
That should fix it https://github.com/cm7sgt/kernel-galaxytab-gb/commit/19142b543aa7ecc19c2afd46df6ce25ac401fdc7
https://github.com/cm7sgt/kernel-galaxytab-gb/commit/0cb062a63d63b17ce3e67bec2ca3ad11c690c493
