### ISSUE TITLE
Bluetooth MAC not correct, general address instead

### ISSUE THREAD

**Issue by ableeker** [cm7sgt/android_device_samsung_galaxytab#29]
The Tab doesn't have the correct bluetooth MAC. Settings > About phone > Status > Bluetooth address display the BT address as 43:29:B0:00:00:00, which I believe is a general address because the last 7 digits are 0. This may cause BT issues.

There's a text file /eft/imei/bt.txt that holds the correct MAC. There's also code in android_device_samsung_aries-common/bdaddr_read.c that reads the MAC from bt.txt and places it in /data/bdaddr. But init.rc does a setprop ro,bt.bdaddr_path to folder data/misc/bluetooth/bt_addr. This folder actually exists but has the same name as the incorrect general address, while /data/bdaddr which should hold the correct address doesn't even exist. I believe bdaddr_read.c is created to fix this actual bug, where the BT MAC isn't set correctly. As it's part of aries_common the fix is included for the Tab, and could be used here as well, but I think it must be implemented for each device, and I suspect this hasn't yet been done for the Tab.

Maybe device_galaxytab.mk needs to be modified to make the fix work? Just a guess, as unfortunately I don't know enough about Android to see what exactly needs to be done to actually fix this bug.

**Comment by cm7sgt** [comment]
Hi, thanks for the report. It is a quite easy fix. I am going to post new binaries soon.
Fixed in https://github.com/cm7sgt/android_device_samsung_p1-common/commit/a1c2badede4670589145640db05a460dac0fbe61

**Comment by cm7sgt** [comment]
New release has been published in XDA thread.

**Comment by ableeker** [comment]
Great job, the fix works beatifully!
