### ISSUE TITLE
No date shown when pulling down notification bar

### ISSUE THREAD

**Issue by andybotting** [cm7sgt/android_device_samsung_galaxytab#4]
This is a trivial one, but I noticed from a build two days ago that when you pull down the notification bar, the date does not appear on the left-side of the bar. This is different from CM7 on my Nexus One.

**Comment by cm7sgt** [comment]
Go to Settings -> CyanogenMod Settings -> Tablet Tweaks, 
Turn off Soft-buttons left check box.
