### ISSUE TITLE
Softkeys do not vibrate

### ISSUE THREAD

**Issue by bethedealer** [cm7sgt/android_device_samsung_galaxytab#6]
Softkeys at the bottom do not vibrate anymore.

**Comment by techomancer** [comment]
Do they vibrate on any other CyanogenMod device?

**Comment by bethedealer** [comment]
I come from Overcome ROM. And the softkeys were working.

**Comment by cm7sgt** [comment]
That's nice. Do they work in CyanogenMod running on any other device?

**Comment by bethedealer** [comment]
I have no idea as I only tried this CyanogenMod on SGT.

**Comment by af974** [comment]
I have had confirmation that with CM7 on desire hd they have softkey vibration. working.

**Comment by cm7sgt** [comment]
great, so maybe there is some way to enable it, i'll check in device/htc/ace

**Comment by rtsp** [comment]
i can confirm (more) that softkey vibrate work on passion, galaxysmtd, captivatemtd and ace

**Comment by cm7sgt** [comment]
Thanks, this is very helpful. I'll check whether they vibrate them from the kernel, becuse I dont think it is from the user space.

**Comment by cm7sgt** [comment]
fixed in https://github.com/cm7sgt/android_device_samsung_galaxytab/commit/a1821d8197b3ced83b1f5849d302e3409cd95e86
it will be included in next update.
