### ISSUE TITLE
Sim card PIN unlock doesnt start automatically when the phone boots.

### ISSUE THREAD

**Issue by chandradithya** [cm7sgt/android_device_samsung_galaxytab#7]
Well after the first boot i got this pop up to unlock my sim card with the number pad to input my pin, it came the instant i booted cm7 for the first time.

But after i rebooted the system,
I never got the unlock sim card option after that so my phone would start up with a sim icon near the network signal icon.
And obv sim features like calls etc wouldnt work.

The work around was to go to settings -> Location and seccurity -> Sim card lock -> (Uncheck the option) Then it asked for the pin code and after de activating it,

The sim icon went off fro the notif bar and it connected to my orperator.

Well its not a crictical issue, just affects the ppl with PIN code for the sim :)

**Comment by cm7sgt** [comment]
I suspect this could be upstream issues. Do you know how other CyanogenMod devices behave with locked SIM cards?

**Comment by chandradithya** [comment]
I installed cm7 on a desire gsm and didnt find this bug. Sounds more like a problem with the small keypad not appearing or something.  Still this doesnt account as a major issue. And its just an issue for ppl using pin locked sim. Deactivate the pin lock and everything works fine.

**Comment by nunocodex** [comment]
With the last update 03 July the pin code works correctly ;)

**Comment by chandradithya** [comment]
Yeah. I just noticed :)

**Comment by cm7sgt** [comment]
Must have been fixed in upstream (main CM7 repo).
